const $ = (id) => document.getElementById(id);
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, signInWithRedirect, getRedirectResult, signOut, GoogleAuthProvider, OAuthProvider } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
const firebaseConfig = { apiKey:'AIzaSyDvCrm9kGb9eUk_u3aLUkKdPIA_8M7Ol3w', authDomain:'moare-auth.firebaseapp.com', projectId:'moare-auth', storageBucket:'moare-auth.firebasestorage.app', messagingSenderId:'696840303220', appId:'1:696840303220:web:4b7c881417e3e0338b5721', measurementId:'G-5FFDHDZJZ5' };
const demoUser = { email: 'student@moa.test', password: 'moa2026!', cardId: 'M-2608-041', spacing: 11.2 };
let activeUser = demoUser, challenge = null, timerId = null;
let firebaseAuth = null;
const firebaseReady = !firebaseConfig.apiKey.startsWith('PASTE_');
if (firebaseReady) firebaseAuth = getAuth(initializeApp(firebaseConfig));
// Keep a demo registry so the admin console can show every locally-created user.
const nativeStorageSet = localStorage.setItem.bind(localStorage);
localStorage.setItem = (key, value) => { if(key==='moaUser'){ try { const user=JSON.parse(value); if(user.email!==demoUser.email){ const users=JSON.parse(localStorage.getItem('moaUsers')||'[]').filter(u=>u.email!==user.email); users.push(user); nativeStorageSet('moaUsers',JSON.stringify(users)); } } catch(_){} } nativeStorageSet(key,value); };
function applyCardPitch(spacing, target) { const p=Math.max(5, spacing*.64); const phase=(spacing*1.37)%p; target.style.setProperty('--card-pitch',`${p}px`); target.style.setProperty('--card-phase',`${phase}px`); target.style.backgroundImage=`repeating-linear-gradient(90deg, transparent 0 ${phase}px, rgba(7,21,29,.72) ${phase}px ${phase+Math.max(1.5,p*.20)}px, transparent ${phase+Math.max(1.5,p*.20)}px ${p}px)`; }

function show(id) { ['welcome','auth','how','admin'].forEach(x => $(x).classList.toggle('hidden', x !== id)); }
function showAdmin(){['welcome','auth','how'].forEach(x=>$(x).classList.add('hidden'));$('admin').classList.remove('hidden');renderAdmin();}
function getUsers(){const list=JSON.parse(localStorage.getItem('moaUsers')||'[]');const legacy=JSON.parse(localStorage.getItem('moaUser')||'null');const users=Array.isArray(list)?list:[];if(legacy&&!users.some(u=>u.email===legacy.email))users.push(legacy);if(!users.length)users.push({...demoUser,name:'데모 사용자'});return users;}
function saveUser(user){const users=getUsers().filter(u=>u.email!==user.email&&u.email!==demoUser.email);users.push(user);localStorage.setItem('moaUsers',JSON.stringify(users));localStorage.setItem('moaUser',JSON.stringify(user));}
function renderAdmin(){const users=getUsers();$('userCount').textContent=users.length;$('pendingCount').textContent=users.length;$('userRows').innerHTML=users.map((u,i)=>`<tr><td>${u.name||'사용자 '+(i+1)}</td><td>${u.email}</td><td><code>${u.cardId}</code></td><td><code>${Number(u.spacing).toFixed(2)} px</code></td><td><span class="status">인쇄 대기</span></td><td><button class="print-btn" data-card="${u.cardId}">겹침 데모</button> <button class="print-btn" data-print="${u.cardId}">투명 필름 인쇄</button></td></tr>`).join('');document.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>demoCard(b.dataset.card));document.querySelectorAll('[data-print]').forEach(b=>b.onclick=()=>printCardInline(b.dataset.print));}
function demoCard(cardId){const u=getUsers().find(x=>x.cardId===cardId)||demoUser;const w=window.open('','_blank','width=760,height=560');if(!w)return;const p=Math.max(6,Number(u.spacing)*.64);w.document.write(`<html><head><title>${u.cardId} 겹침 데모</title><style>body{margin:0;background:#07151d;color:#eaf5f2;font:14px Arial;padding:28px}.screen{width:680px;height:370px;position:relative;background:#dce9e4;overflow:hidden;background-image:repeating-linear-gradient(91deg,transparent 0 ${p*.7}px,#16383d ${p*.7}px ${p}px)}.screen:after{content:'CARD FIT DEMO';position:absolute;inset:0;display:grid;place-items:center;font:bold 48px monospace;color:rgba(10,35,40,.22);letter-spacing:8px}.card{position:absolute;inset:54px 48px;border:1px solid #d7ff54;background:repeating-linear-gradient(90deg,transparent 0 ${p*.42}px,rgba(7,21,29,.75) ${p*.42}px ${p*.62}px,transparent ${p*.62}px ${p}px);mix-blend-mode:multiply}.meta{margin-top:18px;color:#b4c6c3}.meta b{color:#d7ff54}</style></head><body><h2>관리자 전용 카드 겹침 데모</h2><div class="screen"><div class="card"></div></div><p class="meta">사용자: <b>${u.name||u.email}</b> · 카드: <b>${u.cardId}</b> · 고유 간격: <b>${Number(u.spacing).toFixed(2)} px</b></p></body></html>`);w.document.close();}
function printCard(cardId){const u=getUsers().find(x=>x.cardId===cardId)||demoUser;const w=window.open('','_blank','width=700,height=500');if(!w)return;w.document.write(`<html><head><title>${u.cardId} 투명 필름 인쇄</title><style>@page{size:85.6mm 53.98mm;margin:0}html,body{margin:0;padding:0;background:transparent}.card{width:85.6mm;height:53.98mm;background:transparent;color:#0a1b1e;padding:5mm;box-sizing:border-box;font:10px monospace;position:relative;overflow:hidden}.lines{position:absolute;inset:10mm 5mm;background:repeating-linear-gradient(90deg,transparent 0 ${Math.max(2,u.spacing*.20)}px,#0a1b1e ${Math.max(2,u.spacing*.20)}px ${Math.max(3,u.spacing*.36)}px,transparent ${Math.max(3,u.spacing*.36)}px ${Math.max(5,u.spacing*.64)}px)}.bottom{position:absolute;bottom:5mm;left:5mm;right:5mm;display:flex;justify-content:space-between}@media print{.card{background:transparent!important}}</style></head><body><div class="card"><b>인증했무아?</b><span style="float:right">MOIRÉ ID</span><div class="lines"></div><div class="bottom"><b>${u.cardId}</b><b>PITCH ${Number(u.spacing).toFixed(2)} PX</b></div></div><script>window.addEventListener('load',()=>setTimeout(()=>window.print(),150))</script></body></html>`);w.document.close();}
function toast(message) { const t=$('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600); }
function randCode() { return String(Math.floor(100000 + Math.random() * 900000)); }
function canvasPattern(code, spacing, cardPlaced=false) {
  const c=$('moireCanvas'), ctx=c.getContext('2d'), w=c.width, h=c.height;
  ctx.clearRect(0,0,w,h);ctx.fillStyle='#dce9e4';ctx.fillRect(0,0,w,h);
  // Fine vertical carrier lines. The encoded code is only legible when viewed through the matching grille.
  for(let x=-h;x<w+h;x+=spacing){ctx.strokeStyle='#13313a';ctx.lineWidth=1.25;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x-h*.16,h);ctx.stroke();}
  // Encode the code as separated vertical fragments. There is no complete number
  // on the screen: the matching physical grille recombines these fragments optically.
  const ghost=document.createElement('canvas');ghost.width=w;ghost.height=h;const g=ghost.getContext('2d');
  g.font='bold 164px DM Mono, monospace';g.textAlign='center';g.textBaseline='middle';g.fillStyle='#12343b';g.fillText(code,w/2,h/2+4);
  const period=Math.max(5, spacing), reveal=Math.max(1.1, period*.22);
  ctx.save();ctx.globalAlpha=cardPlaced ? .88 : .09;ctx.globalCompositeOperation='multiply';
  for(let x=0;x<w;x+=period){ctx.drawImage(ghost,x,0,Math.min(reveal,w-x),h,x,0,Math.min(reveal,w-x),h);}ctx.restore();
  for(let y=7;y<h;y+=17){ctx.strokeStyle='rgba(7,21,29,.15)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y-12);ctx.stroke();}
}
function startChallenge(){
  challenge={code:randCode(), expires:Date.now()+60000}; $('navLogout').classList.remove('hidden');$('cardId').textContent=activeUser.cardId;$('cardSpacing').textContent=`PITCH — ${activeUser.spacing.toFixed(1)} PX`;
  canvasPattern(challenge.code,activeUser.spacing);applyCardPitch(activeUser.spacing,$('virtualCard'));$('virtualCard').classList.add('hidden');$('retryChallenge').classList.add('hidden');$('loginPanel').classList.add('hidden');$('issuePanel').classList.add('hidden');$('successPanel').classList.add('hidden');$('challengePanel').classList.remove('hidden');
  $('authTitle').innerHTML='카드를 화면에<br />겹쳐 주세요.';$('authText').innerHTML='본인의 무아레 카드로만 확인할 수 있는<br />일회용 코드를 입력합니다.';$('stepNumber').textContent='02'; $('code').value=''; $('verifyError').textContent='';
  clearInterval(timerId); timerId=setInterval(()=>{let left=Math.max(0,challenge.expires-Date.now());let s=Math.ceil(left/1000);$('timer').textContent=`00:${String(s).padStart(2,'0')}`;if(!left){clearInterval(timerId);$('verifyError').textContent='인증 시간이 만료되었습니다. 새 인증을 발급해 주세요.';$('retryChallenge').classList.remove('hidden');$('code').disabled=true;}},250); 
}
async function reset(){clearInterval(timerId);challenge=null;if(firebaseAuth) { try { await signOut(firebaseAuth); } catch (_) {} } activeUser=demoUser;$('navLogout').classList.add('hidden');$('email').value='';$('password').value='';$('loginError').textContent='';$('verifyError').textContent='';$('code').value='';$('code').disabled=false;show('welcome');$('challengePanel').classList.add('hidden');$('issuePanel').classList.add('hidden');$('loginPanel').classList.remove('hidden');$('successPanel').classList.add('hidden');$('authTitle').innerHTML='계정으로<br />입장하세요.';$('authText').innerHTML='등록한 이메일과 비밀번호를 입력해<br />무아레 인증을 시작합니다.';$('stepNumber').textContent='01';}
$('startBtn').onclick=()=>show('auth'); $('backBtn').onclick=reset; $('restartBtn').onclick=reset; $('howBtn').onclick=()=>show('how');$('howBack').onclick=()=>show('welcome');
$('navLogout').onclick=reset;
$('adminBtn').onclick=()=>{ $('adminPassword').value='';$('adminError').textContent='';$('adminLogin').showModal(); };$('adminBack').onclick=()=>{ $('admin').classList.add('hidden');show('welcome'); };$('adminLoginForm').onsubmit=(e)=>{e.preventDefault();if($('adminPassword').value==='admin2026!'){ $('adminLogin').close();showAdmin(); }else $('adminError').textContent='관리자 비밀번호가 올바르지 않습니다.';};$('printAll').onclick=()=>getUsers().forEach(u=>printCard(u.cardId));
$('retryChallenge').onclick=()=>{$('code').disabled=false;startChallenge();};
$('loginForm').onsubmit=(e)=>{e.preventDefault(); const email=$('email').value.trim(), pass=$('password').value; const saved=getUsers().find(u=>u.email===email); if((email===demoUser.email&&pass===demoUser.password)||(saved&&email===saved.email&&pass===saved.password)){activeUser=saved&&email===saved.email?saved:demoUser;startChallenge();}else $('loginError').textContent='이메일 또는 비밀번호를 확인해 주세요.';};
function socialError(err){$('loginError').textContent=location.protocol==='file:'?'로컬 파일에서는 소셜 로그인을 사용할 수 없습니다. GitHub Pages 주소로 접속해 주세요.':err.code==='auth/unauthorized-domain'?'현재 웹 주소가 Firebase 승인 도메인에 없습니다. GitHub Pages 주소로 접속해 주세요.':`소셜 로그인에 실패했습니다 (${err.code||'알 수 없는 오류'}).`}
function finishSocialUser(u,mode){
  const saved=JSON.parse(localStorage.getItem('moaUser')||'null');
  const user=saved&&saved.email===u.email?saved:{name:u.displayName||'',email:u.email||'',password:'',cardId:'M-'+String(Date.now()).slice(-7),spacing:9.5+Math.random()*4};
  localStorage.setItem('moaUser',JSON.stringify(user)); activeUser=user;
  if(mode==='signup'){$('email').value=user.email;$('password').value='';$('issuePanel').classList.add('hidden');$('loginPanel').classList.remove('hidden');$('authTitle').innerHTML='가입이 완료됐어요.<br />로그인해 주세요.';$('authText').innerHTML='소셜 계정과 카드 정보가 저장되었습니다.<br />같은 계정으로 로그인하면 인증이 시작됩니다.';$('loginError').textContent='';toast(`${u.displayName||u.email}님, 회원가입이 완료되었습니다.`)}else{toast(`${u.displayName||u.email}님, 로그인되었습니다.`);startChallenge()}
}
async function startSocial(providerName,mode){
  if(!firebaseReady){toast('먼저 Firebase 설정을 확인해 주세요.');return;}
  try { localStorage.setItem('moaSocialMode',mode); const provider=providerName==='google'?new GoogleAuthProvider():new OAuthProvider('oidc.naver'); await signInWithRedirect(firebaseAuth,provider); }
  catch(err){socialError(err)}
}
if(firebaseAuth){getRedirectResult(firebaseAuth).then(result=>{if(result?.user){finishSocialUser(result.user,localStorage.getItem('moaSocialMode')||'login');localStorage.removeItem('moaSocialMode')}}).catch(socialError)}
 $('googleBtn').onclick=()=>startSocial('google','login');
 $('googleSignupBtn').onclick=()=>startSocial('google','signup');
// 웹 페이지는 운영체제의 화면 캡처를 완전히 차단할 수 없지만, 일반적인 복사·저장·인쇄 단축키와 우클릭을 제한합니다.
document.addEventListener('contextmenu',e=>e.preventDefault());
document.addEventListener('copy',e=>e.preventDefault());
document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&['c','s','p','u'].includes(k)||e.key==='PrintScreen'){e.preventDefault();toast('보호된 화면입니다.');}});
$('signupBtn').onclick=()=>{$('loginPanel').classList.add('hidden');$('issuePanel').classList.remove('hidden');$('authTitle').innerHTML='당신만의 간격을<br />만들어 드릴게요.';$('authText').innerHTML='카드에 들어갈 줄무늬 간격은 발급 후<br />변경되지 않는 개인 고유값입니다.';const p=9.5+Math.random()*4;const id='M-'+String(Date.now()).slice(-7);$('issuePitch').textContent=`PITCH — ${p.toFixed(2)} PX`;$('issueCardId').textContent=id;applyCardPitch(p,$('issuedCard'));$('issuePanel').dataset.pitch=p;$('issuePanel').dataset.cardId=id;};
$('issueBack').onclick=()=>{$('issuePanel').classList.add('hidden');$('loginPanel').classList.remove('hidden');};
$('issueForm').onsubmit=(e)=>{e.preventDefault();const user={name:$('issueName').value.trim(),email:$('issueEmail').value.trim(),password:$('issuePassword').value,cardId:$('issuePanel').dataset.cardId,spacing:Number($('issuePanel').dataset.pitch)};localStorage.setItem('moaUser',JSON.stringify(user));activeUser=user;$('email').value=user.email;$('password').value='';$('issuePanel').classList.add('hidden');$('loginPanel').classList.remove('hidden');$('authTitle').innerHTML='가입이 완료됐어요.<br />로그인해 주세요.';$('authText').innerHTML='발급된 카드 정보를 저장했습니다.<br />이메일과 비밀번호로 로그인하면 인증이 시작됩니다.';$('loginError').textContent='';toast(`${user.name}님의 카드 ${user.cardId}가 발급되었습니다. 이제 로그인해 주세요.`);};
$('verifyForm').onsubmit=(e)=>{e.preventDefault();if(Date.now()>challenge.expires){$('verifyError').textContent='인증 시간이 만료되었습니다.';return;}if($('code').value===challenge.code){clearInterval(timerId);$('challengePanel').classList.add('hidden');$('successPanel').classList.remove('hidden');}else $('verifyError').textContent='코드가 일치하지 않습니다. 카드 위치를 확인해 주세요.';};

// 인쇄 창을 실제 ID-1 카드 크기로 열고, 브라우저가 자동 인쇄를 막을 경우 수동 버튼을 제공합니다.
function printCard(cardId){const u=getUsers().find(x=>x.cardId===cardId)||demoUser;const w=window.open('','_blank','width=430,height=300');if(!w){toast('인쇄 창이 차단되었습니다. 팝업을 허용해 주세요.');return;}const pitch=Number(u.spacing);w.document.write(`<html><head><title>${u.cardId} 투명 필름 인쇄</title><style>@page{size:85.6mm 53.98mm;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0;background:#fff}.card{width:85.6mm;height:53.98mm;background:transparent;color:#0a1b1e;padding:5mm;position:relative;overflow:hidden;font:10px monospace}.lines{position:absolute;inset:10mm 5mm;background:repeating-linear-gradient(90deg,transparent 0 ${Math.max(2,pitch*.20)}px,#0a1b1e ${Math.max(2,pitch*.20)}px ${Math.max(3,pitch*.36)}px,transparent ${Math.max(3,pitch*.36)}px ${Math.max(5,pitch*.64)}px)}.bottom{position:absolute;bottom:5mm;left:5mm;right:5mm;display:flex;justify-content:space-between}.print-now{position:fixed;left:100px;top:10px;padding:8px 14px;background:#d7ff54;border:0;font-weight:bold;cursor:pointer}@media print{.print-now{display:none}}</style></head><body><button class="print-now" onclick="window.print()">프린터 인쇄</button><div class="card"><b>인증했무아?</b><span style="float:right">MOIRÉ ID</span><div class="lines"></div><div class="bottom"><b>${u.cardId}</b><b>PITCH ${pitch.toFixed(2)} PX</b></div></div><script>window.addEventListener('load',()=>{window.focus();setTimeout(()=>window.print(),500)})<\/script></body></html>`);w.document.close();}
function printCardInline(cardId){const u=getUsers().find(x=>x.cardId===cardId)||demoUser;const pitch=Number(u.spacing),sheet=document.createElement('div');sheet.className='print-sheet';sheet.style.setProperty('--gap-a',`${Math.max(2,pitch*.20)}px`);sheet.style.setProperty('--gap-b',`${Math.max(3,pitch*.36)}px`);sheet.style.setProperty('--gap-c',`${Math.max(5,pitch*.64)}px`);sheet.innerHTML=`<b>인증했무아?</b><span style="float:right">MOIRÉ ID</span><div class="lines"></div><div class="bottom"><b>${u.cardId}</b><b>PITCH ${pitch.toFixed(2)} PX</b></div>`;document.body.appendChild(sheet);window.addEventListener('afterprint',()=>sheet.remove(),{once:true});window.print();}

